sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install: pip install tox-travis
script: tox
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE appdb;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres