sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install: pip install tox-travis
script: tox
services:
  - postgresql
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/beer_me/main.py"
  - psql -c "CREATE DATABASE appdb;" -U postgres