"""empty message

Revision ID: 8c374561c752
Revises: 6cab9a6e1441
Create Date: 2019-06-29 21:42:52.494996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c374561c752'
down_revision = '6cab9a6e1441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('beer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='beer_pkey'),
    sa.UniqueConstraint('username', name='beer_username_key')
    )
    # ### end Alembic commands ###
